name: Ci

on: [ "push" ]
permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
        

  fileslist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: List Python files
      run: |
        echo "Listing Python files"
        git ls-files "*.py"
        
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff
        pip install pylint pylint
    - name: Run pylint
      continue-on-error: true
      run: |
        pylint $(git ls-files "*.py") 
    - name: Run ruff
      run: |
        ruff check --fix $(git ls-files "*.py")

        
  superlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort
        pip install black==24.10.0
    - name: Fix imports and formating
      run: |
        isort $(git ls-files "*.py")
        black . 
    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_PYTHON_PYLINT: true
        VALIDATE_PYTHON_RUFF: true
        VALIDATE_PYTHON: true
        VALIDATE_PYTHON_BLACK: true
        continue-on-error: true
        VALIDATE_PYTHON_ISORT: true
        CREATE_LOG_FILE: true  
        DEFAULT_WORKSPACE: ${{ github.workspace }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SUPER_LINTER_LOG_PATH: ./workflows/linter.log
    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: super-linter-log
        path: ./workflows/linter.log
        

  test_coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
    - name: Run unit tests with coverage
      run: |
        pytest --cov=GitProject

        
  todo-to-issue:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          INSERT_ISSUE_URLS: "true"
          CLOSE_ISSUES: "true"
          AUTO_ASSIGN: "true"
      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and Push Changes
        run: |
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin main
          else
            echo "No changes to commit"
          fi
