name: Ci

on: [push, pull_request]
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10","3.12.0"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install ruff
        pip install pytest pytest-cov
    - name: List Python files
      run: |
        echo "Listing Python files"
        git ls-files "*.py"
    - name: Analysing the code with pylint
      continue-on-error: true
      run: |
        pylint $(git ls-files '*.py')
    - name: Ruff linting
      continue-on-error: true 
      run: |
           ruff check .
           ruff format .
           ruff check --fix .
    - name: Run unit tests with coverage
      run: |
        pytest --cov=GitProject
